### PR TITLE
feat:description-section

### PR DESCRIPTION
**Pull request by esther921**
# Description

This is a new feature which is the description section.

## Type of change

- [x] Removed arbitrary values
- [x] Changed from tailwind standard screens to the group's standard screens
- [x] Ensured responsiveness as it is in figma

# How Has This Been Tested?

- [x] npm run dev

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent

### CODE REVIEW

**Review by NNesta — APPROVED** [review]
Well Done

**Review by Fidesnoella — APPROVED** [review]
LGTM

**Review by iamzilfa — APPROVED** [review]
Well done!

**Review by iamzilfa — APPROVED** [review]
Well done!

**Pull request merged**
